-- EventPing Database Setup Script
-- Run this in PostgreSQL before starting the application

-- Create database
CREATE DATABASE eventping;

-- Create user
CREATE USER eventping_user WITH PASSWORD 'eventping_pass';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE eventping TO eventping_user;

-- Connect to the database (run this manually: \c eventping)
-- Then grant schema privileges
GRANT ALL ON SCHEMA public TO eventping_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO eventping_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO eventping_user;

-- The rest will be auto-generated by Hibernate when you start the application
